### PR TITLE
Update for /values-pt-rBR/strings.xml

### PR DESCRIPTION
**Pull request by abacate123**
Fixed typos, translation related issues and added some missing phrases.

### CODE REVIEW

**Comment by creativetrendsapps** [comment]
@abacate123 Thanks for this but these strings a deprecated. Strings are now on OneSky.

**Comment by abacate123** [comment]
Ok, but can't you merge this string with the one from onesky anyways?

**Comment by creativetrendsapps** [comment]
@abacate123 , I would but the strings from onesky are completely up to date. These strings a very old. I invite you to onesky to check out the strings.

**Comment by abacate123** [comment]
K then, thanks.

**Pull request closed without merging**
